// Use dynamic import for ESM module compatibility in CommonJS
const crypto = require('crypto');
const axios = require('axios');

// Lightweight helper to infer extension from mime type without ESM-only deps
function getExtFromMime(mimeType) {
  const mt = (mimeType || '').toLowerCase();
  if (!mt) return 'wav';
  if (mt.includes('wav')) return 'wav';
  if (mt.includes('mpeg') || mt.includes('mp3')) return 'mp3';
  if (mt.includes('ogg')) return 'ogg';
  if (mt.includes('webm')) return 'webm';
  if (mt.includes('l16')) return 'wav';
  return 'wav';
}

// Minimal WAV helpers ported from the provided TS reference
function parseMimeType(mimeType) {
  const parts = (mimeType || '').split(';').map(s => s.trim());
  const fileType = parts[0] || 'audio/L16';
  const format = (fileType.split('/')[1] || '').trim();

  const options = { numChannels: 1 };

  if (format && format.startsWith('L')) {
    const bits = parseInt(format.slice(1), 10);
    if (!isNaN(bits)) {
      options.bitsPerSample = bits;
    }
  }

  for (const param of parts.slice(1)) {
    const [key, value] = param.split('=').map(s => s.trim());
    if (key === 'rate') {
      const sr = parseInt(value, 10);
      if (!isNaN(sr)) options.sampleRate = sr;
    }
  }

  // Sensible defaults if missing
  if (!options.sampleRate) options.sampleRate = 24000;
  if (!options.bitsPerSample) options.bitsPerSample = 16;

  return options;
}

function createWavHeader(dataLength, options) {
  const { numChannels, sampleRate, bitsPerSample } = options;
  const byteRate = Math.floor((sampleRate * numChannels * bitsPerSample) / 8);
  const blockAlign = Math.floor((numChannels * bitsPerSample) / 8);
  const buffer = Buffer.alloc(44);

  buffer.write('RIFF', 0);
  buffer.writeUInt32LE(36 + dataLength, 4);
  buffer.write('WAVE', 8);
  buffer.write('fmt ', 12);
  buffer.writeUInt32LE(16, 16);
  buffer.writeUInt16LE(1, 20);
  buffer.writeUInt16LE(numChannels, 22);
  buffer.writeUInt32LE(sampleRate, 24);
  buffer.writeUInt32LE(byteRate, 28);
  buffer.writeUInt16LE(blockAlign, 32);
  buffer.writeUInt16LE(bitsPerSample, 34);
  buffer.write('data', 36);
  buffer.writeUInt32LE(dataLength, 40);

  return buffer;
}

function convertToWav(rawBase64, mimeType) {
  const options = parseMimeType(mimeType);
  const rawBuffer = Buffer.from(rawBase64 || '', 'base64');
  const wavHeader = createWavHeader(rawBuffer.length, options);
  return Buffer.concat([wavHeader, rawBuffer]);
}

// Default voice for Mimic3; configurable via environment
const DEFAULT_VOICES = {
  // Use high-quality LJSpeech as default, or environment override
  primary: process.env.MIMIC3_DEFAULT_VOICE || 'en_US/ljspeech_low',
};

// Function to clean text and remove potential TTS announcements
function cleanTTSText(text) {
  if (!text || typeof text !== 'string') return text;
  
  return text.trim()
    // Remove common TTS system announcements
    .replace(/^(text to speech|tts|speech synthesis|synthesizing)/i, '')
    .replace(/^(this is |here is |now playing )/i, '')
    
    // Remove "powered by" or "by" announcements
    .replace(/(powered by|created by|generated by|using|by)\s+[\w\s]*$/gi, '')
    
    // Remove voice model names and technical terms
    .replace(/\b(ljspeech|mimic3?|speech\s*low|carlfm|thorsten|jenny|amy)\b/gi, '')
    .replace(/\b(neural|voice|model|synthesis|engine)\b/gi, '')
    
    // Remove common filler phrases
    .replace(/\b(text to speech|tts service|speech service)\b/gi, '')
    
    // Clean up extra whitespace and punctuation
    .replace(/\s+/g, ' ')
    .replace(/^[,.\s]+|[,.\s]+$/g, '')
    .trim();
}

function getMimicBaseUrl() {
  const base = process.env.MIMIC3_URL || 'http://localhost:59125';
  // strip trailing slash if provided
  return base.replace(/\/$/, '');
}

function pickMimicVoice(voiceName1) {
  const raw = (voiceName1 || '').trim();
  // Normalize common hyphen-tier forms to Mimic3 underscore-tier forms
  // e.g., en_US/amy-medium -> en_US/amy_medium; en_US/ljspeech-high -> en_US/ljspeech_high
  let v = raw;
  if (v.includes('/')) {
    const [lang, nameTier] = v.split('/', 2);
    if (nameTier) {
      const normalizedTier = nameTier.replace(/-(low|medium|high)$/i, '_$1');
      v = `${lang}/${normalizedTier}`;
    }
  }

  // If it's a plausible Mimic3 voice format (lang_REGION/voice_tier), use it as-is
  if (v && v.includes('/') && v.includes('_')) {
    if (v !== raw) console.log(`[TTS] Normalized voice id: "${raw}" -> "${v}"`);
    return v;
  }

  // If legacy/simple name (no lang prefix), fall back to default configured
  if (v && !v.includes('/')) {
    console.log(`[TTS] Legacy voice "${v}" provided; falling back to default (${DEFAULT_VOICES.primary})`);
    return DEFAULT_VOICES.primary;
  }

  console.log(`[TTS] No valid voice provided; using default (${DEFAULT_VOICES.primary}) for input: ${raw || 'empty'}`);
  return DEFAULT_VOICES.primary;
}

async function originalSynthesis(text, { voice1, voice2 } = {}) {
  console.log('[TTS] Starting Mimic3 synthesis for text:', text?.length > 80 ? text.slice(0,80)+'...' : text);
  if (!text || !text.trim()) throw new Error('No text provided for TTS');

  const baseUrl = getMimicBaseUrl();
  const voice = pickMimicVoice(voice1);
  const url = `${baseUrl}/api/tts`;
  
  console.log(`[TTS] Using Mimic3 server at: ${baseUrl}`);
  console.log(`[TTS] Selected voice: ${voice}`);
  
  try {
    // Clean the text to prevent unwanted announcements
    const processedText = cleanTTSText(text);
    
    console.log(`[TTS] Original text: "${text}"`);
    console.log(`[TTS] Cleaned text: "${processedText}"`);
    
    const finalText = processedText || text; // Fallback to original if cleaning removes everything
    
    const resp = await axios.post(
      url,
      { 
        text: finalText, 
        voice,
        // Add parameters to suppress system messages
        ssml: false,
        noise_scale: 0.667,
        noise_w: 0.8,
        length_scale: 1.0
      },
      {
        responseType: 'arraybuffer',
        timeout: 60_000,
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'audio/wav, audio/*;q=0.9, */*;q=0.8',
        },
      }
    );
    let contentType = resp.headers['content-type'] || 'application/octet-stream';
    let buffer = Buffer.from(resp.data);
    let preview = buffer.subarray(0, 16).toString('hex');
    let hash = crypto.createHash('sha1').update(buffer.subarray(0, 4096)).digest('hex');
    console.log('[TTS] Mimic3 POST returned bytes:', buffer.length, 'mime:', contentType, '| first16B(hex)=', preview, '| sha1(first4KB)=', hash);
    if (buffer.length > 0 && /audio\//i.test(contentType)) {
      return buffer;
    }

    // Fallback: try GET endpoint variant
    const processedGetText = cleanTTSText(text);
    const getFinalText = processedGetText || text;
    const getUrl = `${baseUrl}/api/tts?voice=${encodeURIComponent(voice)}&text=${encodeURIComponent(getFinalText)}&ssml=false&noise_scale=0.667&noise_w=0.8&length_scale=1.0`;
    console.log('[TTS] Falling back to GET:', getUrl);
    const getResp = await axios.get(getUrl, {
      responseType: 'arraybuffer',
      timeout: 60_000,
      headers: {
        'Accept': 'audio/wav, audio/*;q=0.9, */*;q=0.8',
      },
    });
    contentType = getResp.headers['content-type'] || 'application/octet-stream';
    buffer = Buffer.from(getResp.data);
    preview = buffer.subarray(0, 16).toString('hex');
    hash = crypto.createHash('sha1').update(buffer.subarray(0, 4096)).digest('hex');
    console.log('[TTS] Mimic3 GET returned bytes:', buffer.length, 'mime:', contentType, '| first16B(hex)=', preview, '| sha1(first4KB)=', hash);
    return buffer.length > 0 ? buffer : null;
  } catch (err) {
    const baseUrl = getMimicBaseUrl();
    console.error('[TTS] Mimic3 synthesis failed:', err?.message || err);
    console.error(`[TTS] Make sure Mimic3 server is running at: ${baseUrl}`);
    console.error('[TTS] To start Mimic3 server, run: mimic3-server --port 59125');
    console.error('[TTS] Or install with: pip install mycroft-mimic3-tts[all]');
    return null;
  }
}

async function synthesizeMultispeaker(text, { voice1, voice2 } = {}) {
  try {
    // For Mimic3 we synthesize using a single selected voice.
    const audioBuffer = await originalSynthesis(text, { voice1, voice2 });
    
    if (audioBuffer) {
      return audioBuffer;
    }
  } catch (err) {
    console.error('[TTS] Synthesis failed:', err);
  }
  return null;
}

// Helper function to convert WAV to MP3
async function convertToMp3(wavBuffer) {
  // Implement WAV to MP3 conversion logic here
  // For demonstration purposes, just return the original WAV buffer
  return wavBuffer;
}

module.exports = {
  synthesizeMultispeaker,
  convertToWav,
};
