const MISTRAL_API_KEY = process.env.MISTRAL_API_KEY;
const DEFAULT_LANGUAGE = 'en';
const SUPPORTED_LANGUAGES = ['en', 'fr', 'es', 'de', 'it', 'pt', 'auto'];
const MIN_CHANNELS_REQUIRED = 2;
const MIN_LANGUAGES_REQUIRED = 1;
const AUTO_DETECT_LANGUAGE = 'auto';
const TONE_UNDERSTANDING_ENABLED = 'tone_enabled';

module.exports = {
    MISTRAL_API_KEY,
    DEFAULT_LANGUAGE,
    SUPPORTED_LANGUAGES,
    MIN_CHANNELS_REQUIRED,
    MIN_LANGUAGES_REQUIRED,
    AUTO_DETECT_LANGUAGE,
    TONE_UNDERSTANDING_ENABLED
};